on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: Build

jobs:
  linux:
    name: Build - Linux
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: linux-arm64-gnu
            target: aarch64-unknown-linux-gnu
          - name: linux-arm64-musl
            target: aarch64-unknown-linux-musl
          - name: linux-x64-gnu
            target: x86_64-unknown-linux-gnu
          - name: linux-x64-musl
            target: x86_64-unknown-linux-musl
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.63
          override: true
      - name: Cargo Cache
        uses: Swatinem/rust-cache@v2
      - name: Install cross
        run: cargo install cross
      - name: Build
        run: cross build --release --target ${{ matrix.target }}
      - name: Create artifact
        run: tar -czvf volta-${{ matrix.name }}.tar.gz volta volta-shim volta-migrate
        working-directory: target/${{ matrix.target }}/release
      - name: Upload release artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.name }}
          path: target/${{ matrix.target }}/release/volta-${{ matrix.name }}.tar.gz
